[SysModeDef]
modedef = 0


[Log]
AutoClean = True
LogFileMax = 5


[camera]
id = 0
ReConnectInterval = 1
MaxRetries = 1
size = (640,480)


[text]
InputMaxLen = 20

[picture]
LocalPath = data/local/pics
HisteryPath = data/history/pics
size = (640,480)
PreviewFp = 20
BlockSize = (64,48)
BlockZipSize = 1000

[video]
LocalPath = data/local/vdos
HisteryPath = data/history/vdos
size = (320,240)
PreviewFp = 10
BlockSize = (80,120)
BlockZipSize = 1118
VdoTranMaxTime = 600000

